### ISSUE TITLE
[iOS] Keyboard goes over input field

### ISSUE THREAD

**Issue by Anno008** [mopinion/mopinion-sdk-react-native#4]
### Steps to Reproduce
* Open the mopinion form
* Reach the page that gives the option to provide our contact details.
* Focus the email input field
* The keyboard goes over the input field and the input field isn't visible.

### Actual Behavior
When we focus an input field, for example email, phone number, the keyboard goes over the input field and the field isn't visible. We are still able to scroll till the field becomes visible again, but it might be a bad user experience.

### Expected Behavior
When focusing an input field the page should scroll up so that we can see what we are typing.

### Basic Information
Version with issue: 0.3.1
React Native Version: 0.59.3
React Version: 16.8.6
Device: IPhone XR - 12.1

### Note
This issue is even more pronounced on devices with smaller resolutions.

### Screenshots
Focus on email field (only the elevated placeholder is visible)
![FocusingEmail](https://user-images.githubusercontent.com/26136098/57225920-fb07f800-700d-11e9-8bf7-419c460cfeba.png)
Focus on phone number field (it isn't visible at all)
![FocusingPhoneNumber](https://user-images.githubusercontent.com/26136098/57225957-0f4bf500-700e-11e9-8064-1f1639fd6538.png)

**Comment by Anwardo** [comment]
Thanks again for the detailed description 👍 This one's fixed in 0.3.3 too. On iOS the the input field will now stay in view when the keyboard shows.

**Comment by ledbat** [comment]
Hi there, this also or still happens when selecting a  text input field on a ios iphone X ios 12.2.
you have to scroll down to see the input field after selecting the field.

Expected is that when you select a text field it focusses on the text field even with keyboard shown.
